### PR TITLE
live preview sanity test

### PR DESCRIPTION
**Pull request by harshithad0703**
added live preview test

### CODE REVIEW

**Review by sunil-lakshman — COMMENTED** [review]
@harshithad0703 Update package release version and changelog

**Comment by harshithad0703** [comment]
> @harshithad0703 Update package release version and changelog

will update while adding few more test cases for taxonomy and clearing snyk issues

**Review by sunil-lakshman — APPROVED** [review]
Approved

**Comment by reeshika-h** [comment]
Approved

**Review by reeshika-h — APPROVED** [review]

**Pull request merged**
