### PR TITLE
feat: Support new REST preview service

### PR DESCRIPTION
**Pull request by Deepak-Kharah**
The REST preview service introduces its own preview token and API endpoint for Live preview. This values will be used to fetch entry data for live preview.

Replaced "api.contentstack.io" to "rest-preview.contentstack.com" and replaced `management_token` to `preview_token`

fixes: https://contentstack.atlassian.net/browse/VC-311

### CODE REVIEW

**Review by ishaileshmishra — CHANGES_REQUESTED** [review]
Could you please include both Unit and API tests to cover the live preview updates? @Deepak-Kharah

**Comment by Deepak-Kharah** [comment]
I have added the test cases

**Review by ishaileshmishra — DISMISSED** [review]
Approved 

After it goes live, we will need to include API tests. For now, it appears satisfactory to me.

thanks @Deepak-Kharah ,

**Comment by abhinav-from-contentstack** [comment]
Hi @ishaileshmishra, I have merged changes from @Deepak-Kharah's branch to `v3-next` branch and have resolved merge conflicts in #127 .
Can we close this PR?
cc : @harshithad0703

**Pull request merged**
