### PR TITLE
refactor: :recycle: query function accepts queryObj

### PR DESCRIPTION
**Pull request by nadeem-cs**
Query function earlier had another query function to accept query Object.
Refactored it to base query function.

### CODE REVIEW

**Review by ishaileshmishra — CHANGES_REQUESTED** [review]
Please remove the credentials exposed in the test files

**Review by ishaileshmishra — APPROVED** [review]
approved


thank you

**Comment by ishaileshmishra** [comment]
Please check why  Source Composition Analysis Scan / security (pull_request) is Failing

@nadeem-cs

**Comment by nadeem-cs** [comment]
@ishaileshmishra The source compilation test is failing because of dependency issue with core library. I have already resolved it in the core package and sent for SRE. As soon as new version is released, we'll be good with this test.

**Pull request merged**
